// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/11/2024, 11:39:57 AM
const configMerger = require("/Users/briancao/Work/nuxt-test/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/briancao/Work/nuxt-test/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/briancao/Work/nuxt-test/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/briancao/Work/nuxt-test/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/briancao/Work/nuxt-test/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/briancao/Work/nuxt-test/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/briancao/Work/nuxt-test/plugins/**/*.{js,ts,mjs}","/Users/briancao/Work/nuxt-test/composables/**/*.{js,ts,mjs}","/Users/briancao/Work/nuxt-test/utils/**/*.{js,ts,mjs}","/Users/briancao/Work/nuxt-test/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/briancao/Work/nuxt-test/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/briancao/Work/nuxt-test/app.config.{js,ts,mjs}"] }));

module.exports = config
